[workspace]
resolver = "2"
members = ["cli", "node", "node-wasm", "proto", "rpc", "types"]

[workspace.dependencies]
blockstore = "0.5"
lumina-node = { version = "0.2.0", path = "node" }
lumina-node-wasm = { version = "0.1.1", path = "node-wasm" }
celestia-proto = { version = "0.2.0", path = "proto" }
celestia-rpc = { version = "0.2.0", path = "rpc", default-features = false }
celestia-types = { version = "0.2.0", path = "types", default-features = false }
libp2p = "0.53.2"
nmt-rs = "0.1.0"
celestia-tendermint = { version = "0.32.1", default-features = false }
celestia-tendermint-proto = "0.32.1"

[patch.crates-io]
# Uncomment to apply local changes
#blockstore = { path = "../blockstore" }
#celestia-tendermint = { path = "../celestia-tendermint-rs/tendermint" }
#celestia-tendermint-proto = { path = "../celestia-tendermint-rs/proto" }
#nmt-rs = { path = "../nmt-rs" }
# libp2p = { path = "../../rust-libp2p/libp2p" }
# libp2p-core = { path = "../../rust-libp2p/core" }
# libp2p-identity = { path = "../../rust-libp2p/identity" }
# libp2p-swarm = { path = "../../rust-libp2p/swarm" }
libp2p = { git = "https://github.com/zvolin/rust-libp2p", branch = "v0.53" }
libp2p-core = { git = "https://github.com/zvolin/rust-libp2p", branch = "v0.53" }
libp2p-identity = { git = "https://github.com/zvolin/rust-libp2p", branch = "v0.53" }
libp2p-swarm = { git = "https://github.com/zvolin/rust-libp2p", branch = "v0.53" }

[profile.release]
debug = true
