[workspace]
resolver = "2"
members = ["cli", "node", "node-wasm", "proto", "rpc", "types"]

[workspace.dependencies]
blockstore = "0.7.0"
lumina-node = { version = "0.5.0", path = "node" }
lumina-node-wasm = { version = "0.4.0", path = "node-wasm" }
celestia-proto = { version = "0.4.0", path = "proto" }
celestia-rpc = { version = "0.5.0", path = "rpc", default-features = false }
celestia-types = { version = "0.6.0", path = "types", default-features = false }
libp2p = "0.54.0"
nmt-rs = "0.2.1"
celestia-tendermint = { version = "0.32.2", default-features = false }
celestia-tendermint-proto = "0.32.2"

[patch.crates-io]
# Uncomment to apply local changes
#beetswap = { path = "../beetswap" }
#blockstore = { path = "../blockstore" }
#celestia-tendermint = { path = "../celestia-tendermint-rs/tendermint" }
#celestia-tendermint-proto = { path = "../celestia-tendermint-rs/proto" }
#nmt-rs = { path = "../nmt-rs" }
#libp2p = { path = "../../rust-libp2p/libp2p" }
#libp2p-core = { path = "../../rust-libp2p/core" }
#libp2p-swarm = { path = "../../rust-libp2p/swarm" }

# Uncomment this if you need debug symbols in release.
# Also check node-wasm's `Cargo.toml`.
#[profile.release]
#debug = true
