[workspace]
resolver = "2"
members = ["blockstore", "cli", "node", "node-wasm", "proto", "rpc", "types"]

[workspace.dependencies]
lumina-node = { version = "0.1.0", path = "node" }
lumina-node-wasm = { version = "0.1.0", path = "node-wasm" }
celestia-proto = { version = "0.1.0", path = "proto" }
celestia-rpc = { version = "0.1.0", path = "rpc", default-features = false }
celestia-types = { version = "0.1.0", path = "types", default-features = false }
libp2p = "0.53.2"
nmt-rs = "0.1.0"
celestia-tendermint = { version = "0.32.1", default-features = false }
celestia-tendermint-proto = "0.32.1"
blockstore = { version = "0.1.1", path = "blockstore" }

[patch.crates-io]
# This is a workaround.
# `lumina-node` depends on `beetswap`, which depends on `blockstore`.
# Because `beetswap` is outside of this workspace, cargo thinks that
# it depends on a different `blockstore` crate.
blockstore = { path = "blockstore" }
# Uncomment to apply local changes
#celestia-tendermint = { path = "../celestia-tendermint-rs/tendermint" }
#celestia-tendermint-proto = { path = "../celestia-tendermint-rs/proto" }
#nmt-rs = { path = "../nmt-rs" }

[patch."https://github.com/eigerco/beetswap"]
beetswap = { path = "../beetswap" }
