[workspace]
resolver = "2"
members = ["node", "proto", "rpc", "types"]

[workspace.dependencies]
celestia-proto = { version = "0.1.0", path = "proto" }
celestia-types = { version = "0.1.0", path = "types" }
celestia-rpc = { version = "0.1.0", path = "rpc" }
nmt-rs = { git = "https://github.com/eigerco/nmt-rs.git", rev = "5146800" }
tendermint = { git = "https://github.com/eigerco/celestia-tendermint-rs.git", rev = "dbb4434" }
tendermint-proto = { git = "https://github.com/eigerco/celestia-tendermint-rs.git", rev = "dbb4434" }

[patch.'https://github.com/eigerco/celestia-tendermint-rs.git']
# Uncomment to apply local changes
#tendermint = { path = "../celestia-tendermint-rs/tendermint" }
#tendermint-proto = { path = "../celestia-tendermint-rs/proto" }

[patch.'https://github.com/eigerco/nmt-rs.git']
# Uncomment to apply local changes
#nmt-rs = { path = "../nmt-rs" }
