[package]
name = "celestia-rpc"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
http = "0.2.9"
thiserror = "1.0.40"
jsonrpsee = { version = "0.18.2", features = ["http-client", "macros"] }
celestia-types = { workspace = true }
celestia-proto = { workspace = true }
tendermint-proto = { workspace = true }

[dev-dependencies]
anyhow = "1.0.71"
dotenvy = "0.15.7"
rand = "0.8.5"
tokio = { version = "1.29.0", features = ["rt", "macros"] }
serde_json = "*"
