[package]
name = "celestia-types"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
blockstore = { workspace = true }
celestia-proto = { workspace = true }
nmt-rs = { workspace = true }
tendermint = { workspace = true, features = ["std", "rust-crypto"] }
tendermint-proto = { workspace = true }

base64 = "0.22.1"
bech32 = "0.11.0"
bytes = "1.6.0"
cid = { version = "0.11", default-features = false, features = ["std"] }
const_format = "0.2.31"
ed25519-consensus = { version = "2.1.0", optional = true }
enum_dispatch = "0.3.12"
libp2p-identity = { version = "0.2.7", optional = true }
multiaddr = { version = "0.18.0", optional = true }
multihash = "0.19.1"
rand = { version = "0.8.5", optional = true }
ruint = { version = "1.12.3", features = ["serde"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_repr = { version = "0.1", optional = true }
sha2 = "0.10.6"
thiserror = "1.0.40"

[dev-dependencies]
ed25519-consensus = "2.1.0"
proptest = { version = "1.5.0", default-features = false, features = ["std"] }
rand = "0.8.5"
serde_json = "1.0.97"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
getrandom = { version = "0.2.10", features = ["js"] }
wasm-bindgen-test = "0.3"

[features]
default = ["p2p"]
p2p = ["dep:libp2p-identity", "dep:multiaddr", "dep:serde_repr"]
test-utils = ["dep:ed25519-consensus", "dep:rand"]
wasm-bindgen = ["tendermint/wasm-bindgen"]
