[package]
name = "lumina-cli"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Celestia data availability node implementation in Rust"
authors = ["Eiger <hello@eiger.co>"]
homepage = "https://www.eiger.co"
repository = "https://github.com/eigerco/lumina"
# readme = "README.md" -- It's using the project's root readme as for now, should it have a separate one?
# crates.io is limited to 5 keywords and 5 categories
keywords = ["blockchain", "celestia", "lumina", "node"]
# Must be one of <https://crates.io/category_slugs>
categories = [
  "asynchronous",
  "command-line-utilities",
  "cryptography::cryptocurrencies",
  "network-programming",
  "wasm",
]

[[bin]]
name = "lumina"
path = "src/main.rs"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
celestia-rpc = { workspace = true, features = ["p2p"] }
celestia-types = { workspace = true }
libp2p = { workspace = true }
lumina-node = { workspace = true }

anyhow = "1.0.71"
axum = "0.6.20"
clap = { version = "4.4.4", features = ["derive"] }
console-subscriber = "0.2"
directories = "5.0.1"
dotenvy = "0.15.7"
mime_guess = "2.0"
rust-embed = { version = "8.0.0", features = ["interpolate-folder-path"] }
serde = "1.0.189"
serde_repr = "0.1"
# Upgrading this dependency invalidates existing persistent dbs.
# Those can be restored by migrating between versions:
# https://docs.rs/sled/latest/sled/struct.Db.html#examples-1
sled = "0.34.7"
tokio = { version = "1.29.0", features = ["fs", "macros", "rt-multi-thread"] }
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[build-dependencies]
envy = "0.4"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }

[features]
browser-node = []
