[package]
name = "lumina-cli"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[[bin]]
name = "lumina"
path = "src/main.rs"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
celestia-rpc = { workspace = true, features = ["p2p"] }
celestia-types = { workspace = true }
libp2p = { workspace = true }
lumina-node = { workspace = true }

anyhow = "1.0.71"
axum = "0.7.5"
clap = { version = "4.5.4", features = ["derive"] }
dotenvy = "0.15.7"
mime_guess = "2.0"
rust-embed = "8.3.0"
serde = "1.0.189"
serde_repr = "0.1"
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
