[package]
name = "celestia-proto"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
prost = "0.12.0"
prost-types = "0.12.0"
tendermint-proto = { workspace = true }
serde = { version = "1.0.188", features = ["derive"] }

[build-dependencies]
anyhow = "1.0.75"
prost-build = "0.12.0"

[dev-dependencies]
serde_json = "1.0.105"
