[package]
name = "celestia-proto"
version = "0.3.1"
edition = "2021"
license = "Apache-2.0"
description = "Rust implementation of proto structs used in celestia ecosystem"
authors = ["Eiger <hello@eiger.co>"]
homepage = "https://www.eiger.co"
repository = "https://github.com/eigerco/lumina"
readme = "README.md"
# crates.io is limited to 5 keywords and 5 categories
keywords = ["blockchain", "celestia", "lumina"]
# Must be one of <https://crates.io/category_slugs>
categories = ["encoding", "cryptography::cryptocurrencies"]

[dependencies]
celestia-tendermint-proto = { workspace = true }
prost = "0.12.6"
prost-types = "0.12.6"
serde = { version = "1.0.203", features = ["derive"] }

[build-dependencies]
anyhow = "1.0.86"
prost-build = "0.12.6"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3.42"

[dev-dependencies]
serde_json = "1.0.117"
