name: Release-plz

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main

jobs:
  release-uniffi-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: aarch64-apple-ios,aarch64-apple-ios-sim

      - name: Build node-uniffi for ios
        run: ./node-uniffi/build-ios.sh

      - run: ls -lah ./node-uniffi/ios

  release-uniffi-android:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: aarch64-linux-android,armv7-linux-androideabi,x86_64-linux-android,i686-linux-android

      - name: Install cargo-udeps
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: cargo-ndk@3.5

      - name: Build node-uniffi for android
        run: ./node-uniffi/build-android.sh

      - run: ls -lah ./node-uniffi
      - run: tree -lah ./node-uniffi/app

